### ISSUE TITLE
Keywords can be much more original

### ISSUE THREAD

**Issue by jihedkdiss** [azizamari/Ncodi#33]
You can replace `continue` with `kammel` or `andah` for example 😄 
You can also use `yezzi` instead of `break` 👀

**Comment by azizamari** [comment]
This is what I had in mind but I'm not sure yet that's why I used continue and break in the example.
I will probably use ur suggestion for break (yezzi). As for continue I have to think about it more.
Ps: kamel w o5roj both work right now 
![Screenshot_2021-05-18-12-55-24-658_com android chrome](https://user-images.githubusercontent.com/64031583/118646923-b0aed980-b7d8-11eb-85d8-1d9add63ba7a.jpg)

**Comment by jihedkdiss** [comment]
Super cuz i just saw the example and thought you'll keep them 😃 Good job!
